- model_name: able-smelt-83
  experiment_name: Experiment_on_Bio_ClinicalBERT
  run_id: fbc7ca62e8ed4bf480df35cc635ed9bb
  port: 8080
  host: 127.0.0.1
  mlflow_tracking_uri: postgresql+psycopg2://postgres:postgres@127.0.0.1:5432/postgres
  logging_db: postgresql+psycopg2://postgres:postgres@127.0.0.1:5432/postgres

